### ISSUE TITLE
Lock device generates crash

### ISSUE THREAD

**Issue by Jean-BaptisteC** [meenbeese/Chronos#55]
## How to Reproduce

- Start app and start timer
- Lock device
- Go back to app and wait 1 minutes -> crash
```
FATAL EXCEPTION: main
Process: com.meenbeese.chronos, PID: 17401
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{a4cd227 u0 com.meenbeese.chronos/.services.TimerService c:com.meenbeese.chronos}
at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2204)
at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2175)
at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2470)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8501)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1953)
at android.app.ContextImpl.startForegroundService(ContextImpl.java:1907)
at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:831)
at n2.g.g(SourceFile:1)
at com.meenbeese.chronos.Chronos.onCreate(SourceFile:492)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1379)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7307)
at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2337)
at android.os.Handler.dispatchMessage(Handler.java:107) 
at android.os.Looper.loopOnce(Looper.java:232) 
at android.os.Looper.loop(Looper.java:317) 
at android.app.ActivityThread.main(ActivityThread.java:8501) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878) 
```

## Info

- Device model: `Pixel 6`
- Android version: `Android 14`
- App version: `v1.5.0`

**Comment by meenbeese** [comment]
Can you post a screen recording for this? I can't reproduce it.

**Comment by Jean-BaptisteC** [comment]
Not able to reproduce on 1.8.0
