### ISSUE TITLE
Crash at startup in 1.7.0

### ISSUE THREAD

**Issue by AeliusSaionji** [meenbeese/Chronos#68]
Android 14

```log
FATAL EXCEPTION: main
Process: com.meenbeese.chronos, PID: 11619
N2.b: 1 exceptions occurred.
	at S2.b.f(SourceFile:32)
	at S2.b.g(SourceFile:29)
	at T2.j.g(SourceFile:44)
	at T2.s.run(SourceFile:121)
	at L2.d.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8223)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
  ComposedException 1 :
	java.lang.IllegalStateException: Failed to set TextInputLayout hint (collapsed) color: Unable to find any of fields [defaultHintTextColor, mDefaultTextColor] in com.google.android.material.textfield.TextInputLayout
		at G1.I.a(SourceFile:195)
		at S2.b.g(SourceFile:12)
		at T2.j.g(SourceFile:44)
		at T2.s.run(SourceFile:121)
		at L2.d.run(SourceFile:3)
		at android.os.Handler.handleCallback(Handler.java:958)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loopOnce(Looper.java:205)
		at android.os.Looper.loop(Looper.java:294)
		at android.app.ActivityThread.main(ActivityThread.java:8223)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
	Caused by: java.lang.IllegalArgumentException: Unable to find any of fields [defaultHintTextColor, mDefaultTextColor] in com.google.android.material.textfield.TextInputLayout
		at Q3.l.t(SourceFile:65)
		at G1.I.a(SourceFile:135)
		at S2.b.g(SourceFile:12)
		at T2.j.g(SourceFile:44)
		at T2.s.run(SourceFile:121)
		at L2.d.run(SourceFile:3)
		at android.os.Handler.handleCallback(Handler.java:958)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loopOnce(Looper.java:205)
		at android.os.Looper.loop(Looper.java:294)
		at android.app.ActivityThread.main(ActivityThread.java:8223)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
```

**Comment by marcdw1289** [comment]
Confirmed.
Same on AospExtended, Android 11.

**Comment by m0yP** [comment]
Same; Pixel stock rooted, A14.

**Comment by breiti-oi** [comment]
Confirmed on VollaOS (Android) 13 too

**Comment by meenbeese** [comment]
Working on this, really annoying bug as I can't reproduce it on the simulator.

**Comment by meenbeese** [comment]
Finally got around to fixing this, please test v1.7.1 and see if it works.

**Comment by m0yP** [comment]
> Finally got around to fixing this, please test v1.7.1 and see if it works.

Just updated and indeed, it does not crash anymore!
